name: CI

on:
  workflow_dispatch:  # Manual build option
  pull_request:       # Build for every PR
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # Apple Silicon macs
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # Intel macs
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-24.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup build environment
        uses: ./.github/actions/setup
        with:
          platform: ${{ matrix.platform }}

      - name: build
        env:
          VITE_PODCASTINDEX_API_KEY: ${{ secrets.VITE_PODCASTINDEX_API_KEY }}
          VITE_PODCASTINDEX_API_SECRET: ${{ secrets.VITE_PODCASTINDEX_API_SECRET }}
        run: pnpm tauri build --no-bundle ${{ matrix.args }}
