name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin --bundles app'
            artifact: 'cardo-macos-arm64'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin --bundles app'
            artifact: 'cardo-macos-x64'
          - platform: 'ubuntu-24.04'
            args: '--bundles deb appimage'
            artifact: 'cardo-linux'
          - platform: 'windows-latest'
            args: '--no-bundle'
            artifact: 'cardo-windows'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: setup build environment
        uses: ./.github/actions/setup
        with:
          platform: ${{ matrix.platform }}

      - name: build
        shell: bash
        env:
          VITE_PODCASTINDEX_API_KEY: ${{ secrets.VITE_PODCASTINDEX_API_KEY }}
          VITE_PODCASTINDEX_API_SECRET: ${{ secrets.VITE_PODCASTINDEX_API_SECRET }}
        run: pnpm tauri build ${{ matrix.args }} --config '{"bundle":{"createUpdaterArtifacts":false,"windows":{"certificateThumbprint":null}}}'

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          retention-days: 7
          path: |
            src-tauri/target/**/release/bundle/macos/*.app
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/Cardo.exe
